-- MySQL Script generated by MySQL Workbench
-- vie 08 sep 2017 00:31:44 PET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema campeonato
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `campeonato` ;

-- -----------------------------------------------------
-- Schema campeonato
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `campeonato` DEFAULT CHARACTER SET utf8 ;
USE `campeonato` ;

-- -----------------------------------------------------
-- Table `campeonato`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`persona` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(50) NULL,
  `apaterno` VARCHAR(50) NULL,
  `amaterno` VARCHAR(50) NULL,
  `sexo` INT NULL,
  `dni` CHAR(8) NULL,
  `fecha_nacimiento` DATE NULL,
  `email` VARCHAR(50) NULL,
  `telefono_contacto` VARCHAR(45) NULL,
  `movil_contacto` VARCHAR(45) NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`entrenador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`entrenador` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`entrenador` (
  `identrenador` INT NOT NULL AUTO_INCREMENT,
  `fecha_registro` DATETIME NULL,
  `persona_idpersona` INT NOT NULL,
  PRIMARY KEY (`identrenador`),
  INDEX `fk_entrenador_persona1_idx` (`persona_idpersona` ASC),
  CONSTRAINT `fk_entrenador_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `campeonato`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`delegado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`delegado` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`delegado` (
  `iddelegado` INT NOT NULL,
  `fecha_registro` DATETIME NULL,
  `persona_idpersona` INT NOT NULL,
  PRIMARY KEY (`iddelegado`),
  INDEX `fk_delegado_persona1_idx` (`persona_idpersona` ASC),
  CONSTRAINT `fk_delegado_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `campeonato`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`equipo` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`equipo` (
  `idequipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `nivel` VARCHAR(50) NULL,
  `logo` NVARCHAR(128) NULL,
  `direccion` VARCHAR(50) NULL,
  `fecha_registro` DATE NULL,
  `email_contacto` VARCHAR(50) NULL,
  `telefono_contacto` VARCHAR(45) NULL,
  `estado` TINYINT(1) NULL,
  `entrenador_identrenador` INT NULL,
  `delegado_iddelegado` INT NULL,
  PRIMARY KEY (`idequipo`),
  INDEX `fk_equipo_entrenador1_idx` (`entrenador_identrenador` ASC),
  INDEX `fk_equipo_delegado1_idx` (`delegado_iddelegado` ASC),
  CONSTRAINT `fk_equipo_entrenador1`
    FOREIGN KEY (`entrenador_identrenador`)
    REFERENCES `campeonato`.`entrenador` (`identrenador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipo_delegado1`
    FOREIGN KEY (`delegado_iddelegado`)
    REFERENCES `campeonato`.`delegado` (`iddelegado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`disciplina` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`disciplina` (
  `iddisciplina` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `fecha_registro` DATETIME NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`iddisciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`categoria` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `edad_min` INT NULL,
  `edad_max` INT NULL,
  `fecha_registro` DATETIME NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`jugador` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`jugador` (
  `idjugador` INT NOT NULL AUTO_INCREMENT,
  `num_jugador` VARCHAR(45) NULL,
  `posicion` VARCHAR(45) NULL,
  `estatura` VARCHAR(45) NULL,
  `peso` VARCHAR(45) NULL,
  `tiposangre` VARCHAR(45) NULL,
  `fecha_registro` DATETIME NULL,
  `equipo_idequipo` INT NULL,
  `es_capital` TINYINT(1) NULL,
  `persona_idpersona` INT NOT NULL,
  PRIMARY KEY (`idjugador`),
  INDEX `fk_jugador_equipo1_idx` (`equipo_idequipo` ASC),
  INDEX `fk_jugador_persona1_idx` (`persona_idpersona` ASC),
  CONSTRAINT `fk_jugador_equipo1`
    FOREIGN KEY (`equipo_idequipo`)
    REFERENCES `campeonato`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jugador_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `campeonato`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`modalidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`modalidad` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`modalidad` (
  `disciplina_iddisciplina` INT NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  `equipo_idequipo` INT NOT NULL,
  INDEX `fk_modalidad_disciplina1_idx` (`disciplina_iddisciplina` ASC),
  INDEX `fk_modalidad_categoria1_idx` (`categoria_idcategoria` ASC),
  PRIMARY KEY (`equipo_idequipo`, `categoria_idcategoria`, `disciplina_iddisciplina`),
  CONSTRAINT `fk_modalidad_disciplina1`
    FOREIGN KEY (`disciplina_iddisciplina`)
    REFERENCES `campeonato`.`disciplina` (`iddisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modalidad_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `campeonato`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modalidad_equipo1`
    FOREIGN KEY (`equipo_idequipo`)
    REFERENCES `campeonato`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`arbitro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`arbitro` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`arbitro` (
  `idarbitro` INT NOT NULL,
  `num_certificacion` VARCHAR(45) NULL,
  `fecha_registro` DATETIME NULL,
  `persona_idpersona` INT NOT NULL,
  PRIMARY KEY (`idarbitro`),
  INDEX `fk_arbitro_persona1_idx` (`persona_idpersona` ASC),
  CONSTRAINT `fk_arbitro_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `campeonato`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`usuario` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`usuario` (
  `idusuario` INT NOT NULL,
  `password` VARCHAR(45) NULL,
  `tipo_rol` INT NULL,
  `fecha_registro` DATETIME NULL,
  `persona_idpersona` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_persona1_idx` (`persona_idpersona` ASC),
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `campeonato`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
