-- MySQL Script generated by MySQL Workbench
-- Wed Oct  4 23:00:13 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema campeonato
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `campeonato` ;

-- -----------------------------------------------------
-- Schema campeonato
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `campeonato` DEFAULT CHARACTER SET utf8 ;
USE `campeonato` ;

-- -----------------------------------------------------
-- Table `campeonato`.`equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`equipo` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`equipo` (
  `idequipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `logo` NVARCHAR(128) NULL,
  `email` VARCHAR(50) NULL,
  `telefono` CHAR(9) NULL,
  `color` VARCHAR(50) NULL,
  `fecha_registro` DATETIME NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idequipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`persona` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(50) NULL,
  `apaterno` VARCHAR(50) NULL,
  `amaterno` VARCHAR(50) NULL,
  `sexo` CHAR(1) NULL,
  `tipo_documento` INT NULL,
  `dni` CHAR(8) NULL,
  `fecha_nacimiento` DATE NULL,
  `email` VARCHAR(50) NULL,
  `telefono_contacto` CHAR(9) NULL,
  `estado` INT NULL,
  `fecha_registro` DATETIME NULL,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`disciplina` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`disciplina` (
  `iddisciplina` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `fecha_registro` DATETIME NULL,
  `estado` INT NULL,
  PRIMARY KEY (`iddisciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`categoria` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL,
  `fecha_registro` DATETIME NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`persona_equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`persona_equipo` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`persona_equipo` (
  `persona_idpersona` INT NOT NULL,
  `equipo_idequipo` INT NOT NULL,
  INDEX `fk_jugador_equipo1_idx` (`equipo_idequipo` ASC),
  INDEX `fk_jugador_persona1_idx` (`persona_idpersona` ASC),
  CONSTRAINT `fk_jugador_equipo1`
    FOREIGN KEY (`equipo_idequipo`)
    REFERENCES `campeonato`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jugador_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `campeonato`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`usuario` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`usuario` (
  `idusuario` INT NOT NULL,
  `password` VARCHAR(45) NULL,
  `tipo_rol` INT NULL,
  `fecha_registro` DATETIME NULL,
  `persona_idpersona` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_persona1_idx` (`persona_idpersona` ASC),
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `campeonato`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`evento` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`evento` (
  `idevento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `descripcion` VARCHAR(200) NULL,
  `fecha_inicio` DATETIME NULL,
  `fecha_fin` DATETIME NULL,
  `es_gratuito` TINYINT(1) NULL,
  `costo_evento` DECIMAL(6,2) NULL,
  `estado` INT NULL,
  `fecha_registro` DATETIME NULL,
  PRIMARY KEY (`idevento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`inscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`inscripcion` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`inscripcion` (
  `idinscripcion` INT NOT NULL,
  `equipo_idequipo` INT NOT NULL,
  `evento_idevento` INT NOT NULL,
  `observaciones` VARCHAR(120) NULL,
  `valor_couta` DECIMAL(6,2) NULL,
  `fecha_pago` DATETIME NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idinscripcion`),
  INDEX `fk_inscripcion_equipo1_idx` (`equipo_idequipo` ASC),
  INDEX `fk_inscripcion_evento1_idx` (`evento_idevento` ASC),
  CONSTRAINT `fk_inscripcion_equipo1`
    FOREIGN KEY (`equipo_idequipo`)
    REFERENCES `campeonato`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscripcion_evento1`
    FOREIGN KEY (`evento_idevento`)
    REFERENCES `campeonato`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`extrafield`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`extrafield` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`extrafield` (
  `idextrafield` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(100) NULL,
  `field` VARCHAR(100) NULL,
  `valor` VARCHAR(100) NULL,
  PRIMARY KEY (`idextrafield`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`evento_equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`evento_equipo` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`evento_equipo` (
  `equipo_idequipo` INT NOT NULL,
  `evento_idevento` INT NOT NULL,
  INDEX `fk_evento_equipo_equipo1_idx` (`equipo_idequipo` ASC),
  INDEX `fk_evento_equipo_evento1_idx` (`evento_idevento` ASC),
  CONSTRAINT `fk_evento_equipo_equipo1`
    FOREIGN KEY (`equipo_idequipo`)
    REFERENCES `campeonato`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_equipo_evento1`
    FOREIGN KEY (`evento_idevento`)
    REFERENCES `campeonato`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`modalidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`modalidad` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`modalidad` (
  `idmodalidad` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(150) NULL,
  `categoria_idcategoria` INT NOT NULL,
  `disciplina_iddisciplina` INT NOT NULL,
  PRIMARY KEY (`idmodalidad`),
  INDEX `fk_modalidad_categoria1_idx` (`categoria_idcategoria` ASC),
  INDEX `fk_modalidad_disciplina1_idx` (`disciplina_iddisciplina` ASC),
  CONSTRAINT `fk_modalidad_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `campeonato`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modalidad_disciplina1`
    FOREIGN KEY (`disciplina_iddisciplina`)
    REFERENCES `campeonato`.`disciplina` (`iddisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`evento_modalidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`evento_modalidad` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`evento_modalidad` (
  `evento_idevento` INT NOT NULL,
  `modalidad_idmodalidad` INT NOT NULL,
  INDEX `fk_evento_modalidad_evento1_idx` (`evento_idevento` ASC),
  INDEX `fk_evento_modalidad_modalidad1_idx` (`modalidad_idmodalidad` ASC),
  CONSTRAINT `fk_evento_modalidad_evento`
    FOREIGN KEY (`evento_idevento`)
    REFERENCES `campeonato`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_modalidad_modalidad1`
    FOREIGN KEY (`modalidad_idmodalidad`)
    REFERENCES `campeonato`.`modalidad` (`idmodalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
