-- MySQL Script generated by MySQL Workbench
-- dom 29 oct 2017 14:25:39 PET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema campeonato
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `campeonato` ;

-- -----------------------------------------------------
-- Schema campeonato
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `campeonato` DEFAULT CHARACTER SET utf8 ;
USE `campeonato` ;

-- -----------------------------------------------------
-- Table `campeonato`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`categoria` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `fecha_registro` DATETIME NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`disciplina` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`disciplina` (
  `iddisciplina` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `fecha_registro` DATETIME NULL,
  `estado` INT NULL,
  PRIMARY KEY (`iddisciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`modalidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`modalidad` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`modalidad` (
  `idmodalidad` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(150) NULL,
  `idcategoria` INT NOT NULL,
  `iddisciplina` INT NOT NULL,
  `tipo_genero` CHAR(2) NULL,
  `cantidad_jugadores` INT NULL,
  `num_varones` INT NULL,
  `num_mujeres` INT NULL,
  PRIMARY KEY (`idmodalidad`),
  INDEX `fk_modalidad_categoria1_idx` (`idcategoria` ASC),
  INDEX `fk_modalidad_disciplina1_idx` (`iddisciplina` ASC),
  CONSTRAINT `fk_modalidad_categoria1`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `campeonato`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modalidad_disciplina1`
    FOREIGN KEY (`iddisciplina`)
    REFERENCES `campeonato`.`disciplina` (`iddisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`persona` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(50) NOT NULL,
  `apaterno` VARCHAR(50) NOT NULL,
  `amaterno` VARCHAR(50) NOT NULL,
  `sexo` CHAR(1) NULL,
  `tipo_documento` INT NULL,
  `num_documento` CHAR(8) NULL,
  `fecha_nacimiento` DATE NULL,
  `email` VARCHAR(50) NOT NULL,
  `telefono` CHAR(9) NULL,
  `avatar` NVARCHAR(200) NULL,
  `estado` INT NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`equipo` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`equipo` (
  `idequipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `descripcion` TEXT NULL,
  `logo` NVARCHAR(200) NULL,
  `color` VARCHAR(50) NULL,
  `modalidad_idmodalidad` INT NOT NULL,
  `iddelegado` INT NOT NULL,
  `estado` INT NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  PRIMARY KEY (`idequipo`),
  INDEX `fk_equipo_modalidad_idx` (`modalidad_idmodalidad` ASC),
  INDEX `fk_equipo_persona_idx` (`iddelegado` ASC),
  CONSTRAINT `fk_equipo_modalidad`
    FOREIGN KEY (`modalidad_idmodalidad`)
    REFERENCES `campeonato`.`modalidad` (`idmodalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipo_persona1`
    FOREIGN KEY (`iddelegado`)
    REFERENCES `campeonato`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`persona_equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`persona_equipo` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`persona_equipo` (
  `persona_idpersona` INT NOT NULL,
  `equipo_idequipo` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`perfil` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`usuario` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NOT NULL,
  `password` CHAR(10) NOT NULL,
  `idpersona` INT NOT NULL,
  `idperfil` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_persona_idx` (`idpersona` ASC),
  INDEX `fk_usuario_perfil_idx` (`idperfil` ASC),
  CONSTRAINT `fk_usuario_persona`
    FOREIGN KEY (`idpersona`)
    REFERENCES `campeonato`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_perfil`
    FOREIGN KEY (`idperfil`)
    REFERENCES `campeonato`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`lugar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`lugar` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`lugar` (
  `idlugar` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(150) NULL,
  `latitud` VARCHAR(100) NULL,
  `longitud` VARCHAR(100) NULL,
  `estado` INT NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  PRIMARY KEY (`idlugar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`evento` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`evento` (
  `idevento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `descripcion` TEXT NULL,
  `fecha_inicio` DATETIME NULL,
  `fecha_fin` DATETIME NULL,
  `modo` INT NULL,
  `costo` DECIMAL(6,2) NULL,
  `estado` INT NULL,
  `idlugar` INT NOT NULL,
  `fecha_registro` DATETIME NULL,
  PRIMARY KEY (`idevento`),
  INDEX `fk_evento_lugar1_idx` (`idlugar` ASC),
  CONSTRAINT `fk_evento_lugar1`
    FOREIGN KEY (`idlugar`)
    REFERENCES `campeonato`.`lugar` (`idlugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`deuda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`deuda` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`deuda` (
  `idinscripcion` INT NOT NULL,
  `equipo_idequipo` INT NOT NULL,
  `evento_idevento` INT NOT NULL,
  `observaciones` VARCHAR(120) NULL,
  `valor_couta` DECIMAL(6,2) NULL,
  `fecha_pago` DATETIME NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idinscripcion`),
  INDEX `fk_inscripcion_equipo1_idx` (`equipo_idequipo` ASC),
  INDEX `fk_inscripcion_evento1_idx` (`evento_idevento` ASC),
  CONSTRAINT `fk_inscripcion_equipo1`
    FOREIGN KEY (`equipo_idequipo`)
    REFERENCES `campeonato`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscripcion_evento1`
    FOREIGN KEY (`evento_idevento`)
    REFERENCES `campeonato`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`extrafield`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`extrafield` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`extrafield` (
  `idextrafield` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(100) NULL,
  `field` VARCHAR(100) NULL,
  `valor` VARCHAR(100) NULL,
  PRIMARY KEY (`idextrafield`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`evento_equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`evento_equipo` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`evento_equipo` (
  `equipo_idequipo` INT NOT NULL,
  `evento_idevento` INT NOT NULL,
  INDEX `fk_evento_equipo_equipo1_idx` (`equipo_idequipo` ASC),
  INDEX `fk_evento_equipo_evento1_idx` (`evento_idevento` ASC),
  CONSTRAINT `fk_evento_equipo_equipo1`
    FOREIGN KEY (`equipo_idequipo`)
    REFERENCES `campeonato`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_equipo_evento1`
    FOREIGN KEY (`evento_idevento`)
    REFERENCES `campeonato`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`evento_modalidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`evento_modalidad` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`evento_modalidad` (
  `evento_idevento` INT NOT NULL,
  `modalidad_idmodalidad` INT NOT NULL,
  PRIMARY KEY (`evento_idevento`, `modalidad_idmodalidad`),
  INDEX `fk_evento_has_modalidad_modalidad1_idx` (`modalidad_idmodalidad` ASC),
  INDEX `fk_evento_has_modalidad_evento1_idx` (`evento_idevento` ASC),
  CONSTRAINT `fk_evento_has_modalidad_evento1`
    FOREIGN KEY (`evento_idevento`)
    REFERENCES `campeonato`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_has_modalidad_modalidad1`
    FOREIGN KEY (`modalidad_idmodalidad`)
    REFERENCES `campeonato`.`modalidad` (`idmodalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`equipo_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`equipo_evento` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`equipo_evento` (
  `idequipo` INT NOT NULL,
  `idevento` INT NOT NULL,
  `genero` INT NULL,
  `njugadores` INT NULL,
  `nvarones` INT NULL,
  `nmujeres` INT NULL,
  PRIMARY KEY (`idequipo`, `idevento`),
  INDEX `fk_equipo_has_evento_evento1_idx` (`idevento` ASC),
  INDEX `fk_equipo_has_evento_equipo1_idx` (`idequipo` ASC),
  CONSTRAINT `fk_equipo_has_evento_equipo1`
    FOREIGN KEY (`idequipo`)
    REFERENCES `campeonato`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipo_has_evento_evento1`
    FOREIGN KEY (`idevento`)
    REFERENCES `campeonato`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`equipo_persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campeonato`.`equipo_persona` ;

CREATE TABLE IF NOT EXISTS `campeonato`.`equipo_persona` (
  `equipo_idequipo` INT NOT NULL,
  `persona_idpersona` INT NOT NULL,
  INDEX `fk_equipo_has_persona_persona1_idx` (`persona_idpersona` ASC),
  INDEX `fk_equipo_has_persona_equipo1_idx` (`equipo_idequipo` ASC),
  CONSTRAINT `fk_equipo_has_persona_equipo1`
    FOREIGN KEY (`equipo_idequipo`)
    REFERENCES `campeonato`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipo_has_persona_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `campeonato`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
